---
name: create_vrf
pack: netorchestration-st2-demo
description: Create vrf on pe-router
enabled: true

trigger:
  type: core.st2.webhook
  parameters:
    url: "create-vrf"

action:
  ref: netorchestration-st2-demo.vrf-workflow
  parameters:
    rd: "{{ trigger.body.data.rd }}"
    rt: "{{ trigger.body.data.custom_fields['Route Target'] }}"
    vrf_name: "{{ trigger.body.data.name | replace(' ', '_') }}"
    role: pe-router
